### ISSUE TITLE
 No lexer was found for en 

### ISSUE THREAD

**Issue by rajcybage** [cucumber/gherkin#154]
I have 
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32

`````
C:/RailsInstaller/Ruby2.1.0/lib/ruby/2.1.0/i386-mingw32. Reverting to Ruby lexer.
C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/i18n.rb:108:in `rescue in lexer': No lexer was found for en (cannot load such file -- gherkin/lexer
ported languages are listed in gherkin/i18n.json. (Gherkin::I18n::LexerNotFound)
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/i18n.rb:97:in `lexer'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:139:in `transition_table'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:128:in `build_transition_map'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:124:in `transition_map'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:91:in `initialize'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:68:in `new'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:68:in `push_machine'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/gherkin-2.12.2-x86-mingw32/lib/gherkin/parser/parser.rb:31:in `parse'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/turnip-2.0.2/lib/turnip/builder.rb:124:in `block in build'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/turnip-2.0.2/lib/turnip/builder.rb:122:in `tap'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/turnip-2.0.2/lib/turnip/builder.rb:122:in `build'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/turnip-2.0.2/lib/turnip/rspec.rb:67:in `run'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/turnip-2.0.2/lib/turnip/rspec.rb:18:in `load'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `each'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:106:in `setup'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:92:in `run'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
        from C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rspec-core-3.4.2/exe/rspec:4:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.1.0/bin/rspec:23:in `load'

````

**Comment by aslakhellesoy** [comment]
Please upgrade to Cucumber 2.1 or later, which uses gherkin 3, where this bug is fixed.

**Comment by rajcybage** [comment]
I am using turnip 2.0.2
