### ISSUE TITLE
[python] PyPI package gherkin-official v30.0.3 fails on import

### ISSUE THREAD

**Issue by mdonadoni** [cucumber/gherkin#321]
### 👓 What did you see?

After installing the newly released `gherkin-official` v30.0.3 from PyPI, importing the `Parser` fails:

```console
$ pip install gherkin-official
Collecting gherkin-official
  Using cached gherkin_official-30.0.3-py3-none-any.whl.metadata (1.2 kB)
Collecting typing-extensions>=4 (from gherkin-official)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Using cached gherkin_official-30.0.3-py3-none-any.whl (26 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: typing-extensions, gherkin-official
Successfully installed gherkin-official-30.0.3 typing-extensions-4.12.2

[notice] A new release of pip is available: 23.3.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
```

```console
$ python -c "from gherkin.parser import Parser"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/madonado/.virtualenvs/tmp/lib/python3.12/site-packages/gherkin/parser.py", line 10, in <module>
    from .token_matcher import TokenMatcher
  File "/home/madonado/.virtualenvs/tmp/lib/python3.12/site-packages/gherkin/token_matcher.py", line 10, in <module>
    from .dialect import Dialect
  File "/home/madonado/.virtualenvs/tmp/lib/python3.12/site-packages/gherkin/dialect.py", line 31, in <module>
    with open(DIALECT_FILE_PATH, encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/mdonadoni/.virtualenvs/tmp/lib/python3.12/site-packages/gherkin/gherkin-languages.json'
```

### ✅ What did you expect to see?

Importing the `Parser` should not fail

### 📦 Which tool/library version are you using?

```console
$ pip freeze
gherkin-official==30.0.3
typing_extensions==4.12.2
```

```console
$ python --version
Python 3.12.7
```

### 🔬 How could we reproduce it?

1. Create new virtualenv
2. `pip install gherkin-official`
3. `python -c "from gherkin.parser import Parser"`

### 📚 Any additional context?

Probably related to https://github.com/cucumber/gherkin/pull/290?

**Comment by mpkorstanje** [comment]
Fixed by https://github.com/cucumber/gherkin/pull/316
